/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.myapp;

public class App {
	public static void main(String[] args) {
		int no = 1;
		String name = "아이유";
		String tel = "010-123-123";
		String postNo = "13532";
		String basicAddress = "강남구";
		String detailAddress = "강남빌딩";
		boolean working = true;
		char gender = 'M';
		byte level = 2;
		String createdDate = "2023-01-31";

		System.out.printf("번호: %d\n", no);
		System.out.printf("이름: %s\n", name);
		System.out.printf("전화번호: %s\n", tel);
		System.out.printf("우편번호: %s\n", postNo);
		System.out.printf("기본주소: %s\n", basicAddress);
		System.out.printf("상세주소: %s\n", detailAddress);
		System.out.printf("재직여부: %s\n", working ? "예" : "아니요");
		System.out.printf("성별: %s\n", gender == 'M' ? "남자" : "여자");

		String levelTitle;
		switch (level) {
		case 0: levelTitle = "비전공"; break;
		case 1: levelTitle = "준전공"; break;
		default:
			levelTitle = "전공자";
		}

		System.out.printf("전공: %s\n", levelTitle);
		System.out.printf("생성일: %s\n", createdDate);
	}
}
