/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.myapp;

import java.sql.Date;
import java.util.Scanner;

public class App {

	static final int SIZE = 100;
	static int count = 0;

	static int[] no = new int[SIZE];
	static String[] name = new String[SIZE];
	static String[] tel = new String[SIZE];
	static String[] postNo = new String[SIZE];
	static String[] basicAddress = new String[SIZE];
	static String[] detailAddress = new String[SIZE];
	static boolean[] working = new boolean[SIZE];
	static char[] gender = new char[SIZE];
	static byte[] level = new byte[SIZE];
	static String[] createdDate = new String[SIZE];

	public static void main(String[] args) {

		inputMembers();
		printMembers();

	}

	static void inputMembers() {
		Scanner scanner = new Scanner(System.in);

		for (int i = 0; i < SIZE; i++) {
			no[i] = promptInt(scanner, "번호? ");
			name[i] = promptString(scanner, "이름? ");
			tel[i] = promptString(scanner, "전화번호? ");
			postNo[i] = promptString(scanner, "우편번호? ");
			basicAddress[i] = promptString(scanner, "기본주소? ");
			detailAddress[i] = promptString(scanner, "상세주소? ");
			String title = "0. 백수\n1. 재직\n직업? ";
			working[i] = promptInt(scanner, title) == 1;
			title = "0. 남자\n1. 여자\n성별? ";
			gender[i] =  promptInt(scanner, title) == 0 ? 'M' :  'W';
			title = "0. 비전공자\n1. 준전공자\n2. 전공자\n전공? ";
			level[i] = (byte) promptInt(scanner, title);

			Date today = new Date(System.currentTimeMillis());
			createdDate[i] = today.toString();

			count++;

			System.out.println("계속 입력할거임? (Y/n)");
			String str = scanner.nextLine();
			if (!str.equalsIgnoreCase("Y") && str.length() != 0) {
				break;
			}
		}
		scanner.close();
		System.out.println();
	}

	static void printMembers() {
		for (int i = 0; i < count; i++) {
			System.out.printf("번호: %d\n", no[i]);
			System.out.printf("이름: %s\n", name[i]);
			System.out.printf("전화: %s\n", tel[i]);
			System.out.printf("우편번호: %s\n", postNo[i]);
			System.out.printf("주소1: %s\n", basicAddress[i]);
			System.out.printf("주소2: %s\n", detailAddress[i]);
			System.out.printf("재직자: %s\n", working[i] ? "예" : "아니오");
			System.out.printf("성별: %s\n", gender[i] == 'M' ? "남자" : "여자");

			String levelTitle;
			switch (level[i]) {
			case 0: levelTitle = "비전공"; break;
			case 1: levelTitle = "준전공"; break;
			default:
				levelTitle = "전공자";
			}

			System.out.printf("전공: %s\n", levelTitle);
			System.out.printf("생성일: %s\n", createdDate[i]);
			System.out.println("--------------------------------------");
		}
	}

	static String promptString(Scanner scanner, String title) {
		System.out.println(title);
		return scanner.nextLine();
	}

	static int promptInt(Scanner scanner, String title) {
		return  Integer.parseInt(promptString(scanner,title));
	}
}
