/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.myapp;


public class App {

  public static void main(String[] args) {
    goMainMenu();
    System.out.println("안녕히 가세요ㅋ");
    Prompt.close(); // 프로그램이 사용한 자원 해제
  }

  private static void goMainMenu() {
    while (true ) {
      System.out.println("1. 회원 관리");
      System.out.println("9. 종료");
      System.out.println();
      int menuNo = Prompt.inputInt("menu >> ");

      if (menuNo == 1) {
        MembersHandler.service();
      } else if (menuNo == 9) {
        break;
      } else {
        System.out.println("잘못된 번호 입니다.");
        System.out.println();
      }
    }
  }
}

